import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav/nav";
import { ViewTransitions } from "next-view-transitions";
import { LenisProvider } from "@/app/context/lenisContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <script src="//code.tidio.co/qscpfop7tuw9vaseqly4eopii2xudxpj.js" async></script>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <LenisProvider>
            <Nav />
            {children}
          </LenisProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
